-- Generated by lampe

import Lampe

open Lampe

noir_struct_def «package1-0.0.0»::StructOne<> {
  Field,
}

noir_type_alias «package1-0.0.0»::TypeOne<> := Field;

noir_trait_def «package1-0.0.0»::TraitOne<> [] := {
  method method_one<>(Self) -> Field;
}

