-- Generated by lampe

import Lampe

open Lampe

namespace «package1-0.0.0»
namespace Extracted

noir_struct_def StructOne<> {
  Field,
}

noir_type_alias TypeOne<> := Field;

noir_trait_def TraitOne<> [] := {
  method method_one<>(Self) -> Field;
}

