-- Generated by lampe

import «package1-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «package1-0.0.0»
namespace Extracted

noir_trait_impl[impl_430]<> TraitOne<> for StructOne<> where [] := {
  noir_def method_one<>(self: StructOne<>) -> Field := {
    self.0
  };
}

noir_def function_one<>(input: Field) -> StructOne<> := {
  (#_makeData returning StructOne<>)(input)
}

def Lib.env : Env := Env.mk
  [function_one]
  [impl_430]
