-- Generated by lampe

import «package1-0.0.0».Extracted.GeneratedTypes
import «package1-0.0.0».Extracted.Lib

namespace «package1-0.0.0»
namespace Extracted

def env := «package1-0.0.0».Extracted.Lib.env
